webtalk_init -webtalk_dir E:/workspace/nexys4_ddr_practice/example_4_accel_spi/nexys4_ddr_accel_spi/nexys4_ddr_accel_spi.sim/sim_1/behav/xsim/xsim.dir/accel_spi_rw_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 30 19:12:46 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "67a7fcca-54a4-464b-91d9-298f022cd293" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6dd97625897c44f2bf005a6a553e60a9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "96" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 1600 Six-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3200 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "12" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "92 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "3 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "20" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "10" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "50896_KB" -context "xsim\\usage"
webtalk_transmit -clientid 751272377 -regid "" -xml E:/workspace/nexys4_ddr_practice/example_4_accel_spi/nexys4_ddr_accel_spi/nexys4_ddr_accel_spi.sim/sim_1/behav/xsim/xsim.dir/accel_spi_rw_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/workspace/nexys4_ddr_practice/example_4_accel_spi/nexys4_ddr_accel_spi/nexys4_ddr_accel_spi.sim/sim_1/behav/xsim/xsim.dir/accel_spi_rw_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/workspace/nexys4_ddr_practice/example_4_accel_spi/nexys4_ddr_accel_spi/nexys4_ddr_accel_spi.sim/sim_1/behav/xsim/xsim.dir/accel_spi_rw_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
