webtalk_init -webtalk_dir E:/workspace/nexys4_ddr_practice/example_4_accel_spi/nexys4_ddr_accel_spi/nexys4_ddr_accel_spi.sim/sim_1/behav/xsim/xsim.dir/accel_spi_rw_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 31 01:07:14 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "67a7fcca-54a4-464b-91d9-298f022cd293" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6dd97625897c44f2bf005a6a553e60a9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "130" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 1600 Six-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3200 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "15001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.84_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13952_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1265219442 -regid "" -xml E:/workspace/nexys4_ddr_practice/example_4_accel_spi/nexys4_ddr_accel_spi/nexys4_ddr_accel_spi.sim/sim_1/behav/xsim/xsim.dir/accel_spi_rw_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/workspace/nexys4_ddr_practice/example_4_accel_spi/nexys4_ddr_accel_spi/nexys4_ddr_accel_spi.sim/sim_1/behav/xsim/xsim.dir/accel_spi_rw_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/workspace/nexys4_ddr_practice/example_4_accel_spi/nexys4_ddr_accel_spi/nexys4_ddr_accel_spi.sim/sim_1/behav/xsim/xsim.dir/accel_spi_rw_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
